@startuml

' Обобщённая роль пользователя веб-системы
:Пользователь \\nсистемы: <|-- :Гость:
:Пользователь \\nсистемы: <|-- :Зарегистрированный \\nпользователь:
:Пользователь \\nсистемы: <|-- :Администратор:

' -------- Гость --------
:Гость: --> (Просмотр \\nглавной страницы)
:Гость: --> (Поиск \\nрейсов \\nбез авторизации)
:Гость: --> (Регистрация \\nв системе)
:Гость: -left-> (Авторизация \\nв системе)

(Поиск \\nрейсов \\nбез авторизации) ..> (Ввод \\nстанций и даты):включает
(Поиск \\nрейсов \\nбез авторизации) ..> (Просмотр \\nсписка рейсов):включает
(Регистрация \\nв системе) ..> (Заполнение \\nрегистрационной формы):включает
(Авторизация \\nв системе) ..> (Ввод \\nучётных данных):включает

' -------- Зарегистрированный пользователь --------
:Зарегистрированный \\nпользователь: --> (Поиск \\nрейсов)
:Зарегистрированный \\nпользователь: --> (Просмотр \\nдоступных мест)
:Зарегистрированный \\nпользователь: --> (Покупка \\nбилета)
:Зарегистрированный \\nпользователь: --> (Просмотр \\nмоих билетов)
:Зарегистрированный \\nпользователь: --> (Выгрузка \\nмоих билетов)

(Поиск \\nрейсов) ..> (Ввод \\nстанций и даты):включает
(Поиск \\nрейсов) ..> (Просмотр \\nсписка рейсов):включает

(Просмотр \\nдоступных мест) ..> (Загрузка \\nсхемы вагона):включает
(Просмотр \\nдоступных мест) ..> (Выбор \\nместа):включает

(Покупка \\nбилета) ..> (Выбор \\nрейса и места):включает
(Покупка \\nбилета) ..> (Ввод \\nданных пассажира):включает
(Покупка \\nбилета) ..> (Подтверждение \\nпокупки):включает
(Покупка \\nбилета) <.left. (Отмена \\nоформления):расширяет

(Просмотр \\nмоих билетов) ..> (Получение \\nсписка билетов \\nиз БД):включает
(Выгрузка \\nмоих билетов) ..> (Формирование \\nCSV-отчёта):включает

' -------- Администратор --------
:Администратор: --> (Управление \\nпоездами)
:Администратор: --> (Управление \\nстанциями)
:Администратор: --> (Управление \\nмаршрутами)
:Администратор: --> (Управление \\nрейсами)
:Администратор: --> (Просмотр \\nстатистики)
:Администратор: --> (Выгрузка \\nотчётных данных)
:Администратор: -right-> (Авторизация \\nв системе)

(Управление \\nпоездами) ..> (Добавление/\\nредактирование/\\nудаление поезда):включает
(Управление \\nстанциями) ..> (Добавление/\\nредактирование/\\nудаление станции):включает
(Управление \\nмаршрутами) ..> (Настройка \\nсвязей поезд–станции):включает
(Управление \\nрейсами) ..> (Создание \\nрейсов по датам):включает

(Просмотр \\nстатистики) ..> (Получение \\nданных из БД):включает
(Выгрузка \\nотчётных данных) ..> (Формирование \\nCSV-отчётов):включает

@enduml